blank_issues_enabled: true
contact_links:
  - name: Questions or Discussion
    url: https://bunprinceton.github.io/tracer-workspace/contribute/
    about: Not sure which template to use? Read more about how to suggest changes.
